# Generated by Django 3.2.6 on 2022-01-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Город', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='NoName', max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('мужчина', 'm'), ('женщина', 'w')], default='', max_length=7, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='NoLastName', max_length=100, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=300, verbose_name='О себе'),
        ),
    ]
