# Generated by Django 3.2.6 on 2022-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.TextField(max_length=20, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.TextField(max_length=20, null=True, verbose_name='Долгота'),
        ),
    ]
