# Generated by Django 3.2.6 on 2022-01-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220128_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(max_length=20, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(max_length=20, null=True, verbose_name='Долгота'),
        ),
    ]
