# Generated by Django 3.2.6 on 2022-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_watermark_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='watermark_image',
            field=models.ImageField(default='default.jpg', upload_to='watermark_images'),
        ),
    ]
