# Generated by Django 3.2.6 on 2022-01-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220128_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermark',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
