# Generated by Django 3.2.6 on 2022-01-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_watermark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watermark',
            name='user',
        ),
        migrations.AddField(
            model_name='watermark',
            name='profile',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
